dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11

install:
  - cd ..
  - git clone https://github.com/kbase/jars
  - export JARSDIR=`pwd`/jars/lib/jars/
  - cd -

script:
  # - ant javadoc javadoc is a mess. Pointless testing for now.
  - make test-coverage

after_success:
  - ls test-reports
  - bash <(curl -s https://codecov.io/bash) -f test-reports/coverage-report.xml

